import { providerError } from "./errors.js";
import type { ProviderAdapter, ProviderCapabilities, ProviderRunEvent, ProviderRunInput, ProviderRunResult, ProviderSession, SessionCheckpoint } from "./types.js";

export type CodexTransport = { request(method: string, params: Record<string, unknown>, correlationId: string): Promise<{ id?: string; result?: Record<string, unknown>; error?: { message: string; code?: string } }>; events?(correlationId: string): AsyncIterable<Record<string, unknown>>; cancel?(sessionId: string, turnId: string, correlationId: string): Promise<void> };
export class CodexAppServerAdapter implements ProviderAdapter {
  readonly name = "codex"; readonly capabilities: ProviderCapabilities = { streaming: true, toolCalls: true, resume: true, cancellation: true };
  constructor(private readonly transport?: CodexTransport, private readonly config: { url?: string; command?: string; model?: string } = {}) {}
  private requireTransport(): CodexTransport { if (!this.transport) throw new Error("Codex App Server transport is not configured"); return this.transport; }
  async createSession(input: { model?: string; workspacePath?: string } = {}): Promise<ProviderSession> { const c = crypto.randomUUID(); const r = await this.requireTransport().request("thread/start", { ...(input.model ?? this.config.model ? { model: input.model ?? this.config.model } : {}), ...(input.workspacePath ? { cwd: input.workspacePath } : {}) }, c); const thread = r.result?.thread as Record<string, unknown> | undefined; const sessionId = thread?.id ?? r.result?.threadId; if (r.error || !sessionId) throw new Error(r.error?.message ?? "Codex thread creation failed"); const now = new Date().toISOString(); return { provider: this.name, ...(input.model ?? this.config.model ? { model: input.model ?? this.config.model } : {}), providerSessionId: String(sessionId), status: "active", createdAt: now, updatedAt: now }; }
  async resumeSession(session: ProviderSession): Promise<ProviderSession> { const r = await this.requireTransport().request("thread/resume", { threadId: session.providerSessionId }, crypto.randomUUID()); if (r.error) throw new Error(r.error.message); return { ...session, status: "active", updatedAt: new Date().toISOString() }; }
  async checkpoint(session: ProviderSession): Promise<SessionCheckpoint> { return { provider: session.provider, providerSessionId: session.providerSessionId, ...(session.providerTurnId ? { providerTurnId: session.providerTurnId } : {}), sequence: 0, state: {}, createdAt: new Date().toISOString() }; }
  async *run(input: ProviderRunInput): AsyncGenerator<ProviderRunEvent, ProviderRunResult> { const t = this.requireTransport(); const session = input.session ?? await this.createSession({ model: input.model, ...(input.workspacePath ? { workspacePath: input.workspacePath } : {}) }); const correlationId = input.correlationId ?? crypto.randomUUID(); const r = await t.request("turn/start", { threadId: session.providerSessionId, input: [{ type: "text", text: input.input }], ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}) }, correlationId); if (r.error) { const error = providerError(r.error.message, "provider", "retryable", { code: r.error.code ?? "CODEX_ERROR", provider: this.name, correlationId }); yield { type: "provider.error", error, correlationId }; throw new Error(error.message); } const turnId = String(r.result?.turnId ?? r.id ?? correlationId); yield { type: "turn.started", turnId, correlationId }; let text = ""; if (t.events) for await (const e of t.events(session.providerSessionId)) { const type = String(e.type); if (type === "turn.delta") { const delta = String(e.text ?? ""); text += delta; yield { type: "turn.delta", turnId, text: delta, correlationId }; } else if (type === "tool.started" || type === "tool.completed") yield { type, turnId, toolName: String(e.toolName ?? "unknown"), ...(e.output ? { output: String(e.output) } : {}), correlationId } as ProviderRunEvent; } yield { type: "turn.completed", turnId, text, correlationId }; return { turnId, text, session: { ...session, providerTurnId: turnId, status: "completed", updatedAt: new Date().toISOString() } }; }
  async *cancel(session: ProviderSession, turnId: string, correlationId = crypto.randomUUID()): AsyncGenerator<ProviderRunEvent> { await this.requireTransport().cancel?.(session.providerSessionId, turnId, correlationId); yield { type: "turn.cancelled", turnId, correlationId }; }
}
