import { useState } from "react";
type Props = { api: string; workstreamId: string; status: string; onStatus: (status: string) => void };
const commands = [{ key: "pause", label: "Pause" }, { key: "resume", label: "Resume" }, { key: "complete", label: "Complete" }, { key: "emergency-stop", label: "Emergency stop" }];
export function WorkstreamControls({ api, workstreamId, status, onStatus }: Props) {
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false); const [goal, setGoal] = useState(""); const [workspace, setWorkspace] = useState("/workspaces/academic-paper-buddy"); const terminal = ["completing", "completed", "archived", "emergency_stopped"].includes(status);
  async function createWorkstream() { if (!goal.trim()) return; setBusy("create"); try { const response = await fetch(`${api}/api/workstreams`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ goal: goal.trim(), flavor: "software-development", workspaceRoot: workspace.trim(), tool: "mock", model: "deterministic" }) }); if (!response.ok) throw new Error("Unable to create Workstream"); setShowCreate(false); setGoal(""); window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(null); } }
  async function start() { setBusy("start"); try { const response = await fetch(`${api}/api/workstreams/${workstreamId}/start`, { method: "POST" }); const result = await response.json() as { status?: string; error?: string }; if (!response.ok) throw new Error(result.error ?? "Start failed"); if (result.status) onStatus(result.status); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(null); } }
  async function command(key: string) { setBusy(key); try { const response = await fetch(`${api}/api/workstreams/${workstreamId}/${key}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ commandId: `${key}-${Date.now()}` }) }); const result = await response.json() as { status?: string; error?: string; message?: string }; if (!response.ok) throw new Error(result.message ?? result.error ?? `Command ${key} failed`); if (result.status) onStatus(result.status); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(null); } }
  async function approval(decision: "complete" | "reject") { setBusy(`approval-${decision}`); try { const response = await fetch(`${api}/api/workstreams/${workstreamId}/approval`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ commandId: `approval-${decision}-${Date.now()}`, decision }) }); const result = await response.json() as { status?: string; error?: string }; if (!response.ok) throw new Error(result.error ?? "Approval failed"); if (result.status) onStatus(result.status); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(null); } }
  const waiting = status === "waiting_for_human" || status === "completing";
  return <div className="workstream-controls"><span className="controls-label">Workstream controls</span><div className="control-actions"><button className="secondary" onClick={() => setShowCreate((value) => !value)}>+ New Workstream</button>{status === "draft" && <button className="approve" disabled={busy !== null} onClick={() => void start()}>{busy === "start" ? "Starting…" : "Start Workstream"}</button>}{commands.map((item) => <button key={item.key} className={item.key === "emergency-stop" ? "danger" : "secondary"} disabled={status === "draft" || terminal || busy !== null || (item.key === "pause" && status === "paused") || (item.key === "resume" && status !== "paused")} onClick={() => void command(item.key)}>{busy === item.key ? "Working…" : item.label}</button>)}{waiting && <><button className="approve" disabled={busy !== null} onClick={() => void approval("complete")}>Approve & complete</button><button className="secondary" disabled={busy !== null} onClick={() => void approval("reject")}>Reject</button></>}{error && <p className="control-error">{error}</p>}</div>{showCreate && <div className="new-workstream-form"><label>Goal<textarea value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="What should this Workstream accomplish?" rows={3} /></label><label>Flavor<select><option>Software development</option></select></label><label>Workspace path<input value={workspace} onChange={(event) => setWorkspace(event.target.value)} /></label><label>Provider / model<select><option>Mock · deterministic</option><option disabled>Codex · coming soon</option><option disabled>Claude · coming soon</option></select></label><button className="primary" disabled={!goal.trim() || busy !== null} onClick={() => void createWorkstream()}>{busy === "create" ? "Creating…" : "Create Workstream"}</button></div>}</div>;
}
